//
//  SearchRouter.swift
//  SwiftTwitter
//
//  Created by Matheus Lima on 11/04/19.
//  Copyright (c) 2019 Matheus Lima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic {
    func routeToTimeline(segue: UIStoryboardSegue?)
}

protocol SearchDataPassing {
    var dataStore: SearchDataStore? { get set }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing {
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?
    
    // MARK: Routing
    
    func routeToTimeline(segue: UIStoryboardSegue?) {
        if let segue = segue {
            guard let destinationVC = segue.destination as? TimelineViewController,
                  var destinationDS = destinationVC.router?.dataStore else {
                return
            }
            
            passDataToTimeline(source: dataStore!, destination: &destinationDS)
        } else {
            guard let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "TimelineViewController") as? TimelineViewController, var destinationDS = destinationVC.router?.dataStore else {
                return
            }
            
            self.passDataToTimeline(source: dataStore!, destination: &destinationDS)
            self.navigateToTimeline(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    private func navigateToTimeline(source: SearchViewController, destination: TimelineViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    private func passDataToTimeline(source: SearchDataStore, destination: inout TimelineDataStore) {
        guard let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row else {
            return
        }
        
        destination.user = source.tweets?[selectedRow].user
    }
}
