//
//  SplashModels.swift
//  SwiftTwitter
//
//  Created by Matheus Lima on 03/05/19.
//  Copyright (c) 2019 Matheus Lima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Splash {
    enum VerifyCredentials {
        struct Request { }
        
        struct Response {
            var userID: String?
            var userProfileImageURL: URL?
        }
        
        struct ViewModel {
            var userID: String?
            var userProfileImageURL: URL?
        }
    }
}
