//
//  SplashPresenter.swift
//  SwiftTwitter
//
//  Created by Matheus Lima on 03/05/19.
//  Copyright (c) 2019 Matheus Lima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashPresentationLogic {
    func presentMainScreen(response: Splash.VerifyCredentials.Response)
    func presentLoginScreen()
}

class SplashPresenter: SplashPresentationLogic {
    weak var viewController: SplashDisplayLogic?
    
    func presentLoginScreen() {
        viewController?.displayLoginScreen()
    }
    
    func presentMainScreen(response: Splash.VerifyCredentials.Response) {
        let userID = response.userID
        let userProfileImageURL = response.userProfileImageURL
        let viewModel = Splash.VerifyCredentials.ViewModel(userID: userID, userProfileImageURL: userProfileImageURL)
        self.viewController?.displayMainScreen(viewModel: viewModel)
    }
}
