//
//  SplashRouter.swift
//  SwiftTwitter
//
//  Created by Matheus Lima on 03/05/19.
//  Copyright (c) 2019 Matheus Lima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SplashRoutingLogic {
    func routeToMainScreen()
    func routeToLoginScreen()
}

protocol SplashDataPassing {
    var dataStore: SplashDataStore? { get }
}

class SplashRouter: NSObject, SplashRoutingLogic, SplashDataPassing {
    weak var viewController: SplashViewController?
    var dataStore: SplashDataStore?
    
    // MARK: Routing
    
    func routeToMainScreen() {
        AppDelegate.shared.rootViewController.switchToMainScreen(
            userID: self.dataStore?.userID,
            userProfileImageURL: self.dataStore?.userProfileImageURL
        )
    }
    
    func routeToLoginScreen() {
        AppDelegate.shared.rootViewController.switchToLogout()
    }
}
