//
//  LoginPresenter.swift
//  SwiftTwitter
//
//  Created by Matheus Lima on 02/05/19.
//  Copyright (c) 2019 Matheus Lima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentLoginSuccess(response: Login.OAuth.Response)
    func presentLoginFailure(response: Login.OAuth.Response)
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?
    
    func presentLoginSuccess(response: Login.OAuth.Response) {
        let viewModel = Login.OAuth.ViewModel()
        viewController?.displayLoginSuccess(viewModel: viewModel)
    }
    
    func presentLoginFailure(response: Login.OAuth.Response) {
        guard let error = response.error else { return }
        let viewModel = Login.OAuth.ViewModel(errorMessage: error.message)
        viewController?.displayError(viewModel: viewModel)
    }
}
