//
//  LoginRouter.swift
//  SwiftTwitter
//
//  Created by Matheus Lima on 02/05/19.
//  Copyright (c) 2019 Matheus Lima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func routeToSearch()
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    
    func routeToSearch() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        guard let destinationVC = storyboard.instantiateViewController(
            withIdentifier: "SearchViewController") as? SearchViewController else { return }
        
        guard let destinationRouter = destinationVC.router, var destinationDS = destinationRouter.dataStore else {
            return
        }
        
        guard let dataStore = dataStore, let viewController = viewController else { return }
        
        passDataToSearch(source: dataStore, destination: &destinationDS)
        navigateToSearch(source: viewController)
    }
    
    // MARK: Navigation
    
    func navigateToSearch(source: LoginViewController) {
        source.performSegue(withIdentifier: "LoginSegue", sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToSearch(source: LoginDataStore, destination: inout SearchDataStore) {
        destination.userID = source.userID
    }
}
